[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

[colors.selection]
text = '#cdd6f4'
background = '#7d5d56'

[colors.cursor]
text = '#1e1e2e'
cursor = '#f5e0dc'

[colors.normal]
black   = '#181825'
red     = '#ff7572'
green   = '#93f57a'
yellow  = '#ffe472'
blue    = '#e8d0cc'
magenta = '#715f5c'
cyan    = '#f5e0dc'
white   = '#fff1ef'

[colors.bright]
black   = '#9f9593'
red     = '#ffa19f'
green   = '#b7ffa5'
yellow  = '#ffeea5'
blue    = '#ffece8'
magenta = '#ffefec'
cyan    = '#fff5f3'
white   = '#fff9f8'
